### ISSUE TITLE
Add El Farol problem under Mesa framework

### ISSUE THREAD

**Issue by danielxu05** [projectmesa/mesa#1048]
**What's the problem this feature will solve?**

I could not access to the dev mailing list, so I create a ticket here. There is no El Farol example in the mesa pakcage 

**Describe the solution you'd like**

I implemented el Farol simulation problem under mesa framework and would like to contribute it to mesa package as an example project. 

**Additional context**

**Comment by tpike3** [comment]
@danielxu05 Sorry for the late reply, that is great!

Regarding the dev mailing list, we switched to [discussion](https://github.com/projectmesa/mesa/discussions) instead of the dev mailing to keep everything consolidated. 

If you add it to the [examples folder](https://github.com/projectmesa/mesa/tree/main/examples) and do a pull request we can bring it in. 

Please take a look at the [contributors guide](https://github.com/projectmesa/mesa/blob/main/CONTRIBUTING.rst)
