### ISSUE TITLE
How to model the agents' steps by a continuous time,like each hour?

### ISSUE THREAD

**Issue by seeingwu** [projectmesa/mesa#1054]
**What's the problem this feature will solve?**

Hi, maybe there is a way I didn't find out to realize that each agent will advance its step by an hour with a different time schedule. For example, my agent is the pupil; some pupils will go to school from 8:00 to 9:00, and while some will start their commuting from 9:00 to 10:00. The whole day may be divided into 24 hours, and agents will have an individual schedule to arrange their daily activities. How to represent the 24 hours in MESA?
**Describe the solution you'd like**

I have a very naive solution, which is using the self.time to take modulo of 24 in the step function of agent class, but it seems very redundant. Is there any other way to do that?
**Additional context**

In addition, in the visualization module, how to show the time or date in the axis rather than step?
Best regards
Sijin

**Comment by tpike3** [comment]
@seeingwu There is a couple options for time depending on what specifically you are trying to accomplish.

- Based on your description you may be looking for [staged activation](https://github.com/projectmesa/mesa/blob/72efecaacbc612927ff640f699f2cce4c01bc34e/mesa/time.py#L152). The class description describes how to implement
- As for keeping track of the time, your solution isn't naïve, I would just put it as part of the model instantiation class so it is only calculated once per step instead of every agent, every step. 
- As for the charts take at look at the [charts in the examples](https://github.com/projectmesa/mesa/blob/main/examples/charts/charts/server.py) and that should help you find a solution.


Let me know if this gets your through.

**Comment by jackiekazil** [comment]
I am not sure there is any action that needs to be taken at this time. I am going to close this issue for now.
