### ISSUE TITLE
StagedActivation Example

### ISSUE THREAD

**Issue by rhari008** [projectmesa/mesa#1125]
**What's the problem this feature will solve?**
Please can you provide an example for staged activation? 

**Describe the solution you'd like**
I am trying to solve a problem where I wanted the first phase of agents to interact randomly. However, starting next phase - learn from the experience of interaction and then interact only with those that are good. I guess I can use staged activation for this purpose. 

I tried to do it without staged activation by calling the step twice and activating new agents in the second call - Obviously it didnt work the way I wanted.

**Comment by EwoutH** [comment]
Yes, I agree this is really needed. Related to #657.

**Comment by EwoutH** [comment]
Since we're moving away from schedulers, this is no longer needed. You can do this now with AgentSet behavior:

```Python
class SomeModel(Model)
    ...
    def step(self):
        """
        Perform the model step in two stages:
        - First, all cells assume their next state (whether they will be dead or alive)
        - Then, all cells change state to their next state
        """
        self.agents.do("determine_state")
        self.agents.do("assume_state")

```
See as examples:
- [hex_snowflake](https://github.com/projectmesa/mesa-examples/tree/main/examples/hex_snowflake)
- [color_patches](https://github.com/projectmesa/mesa-examples/tree/main/examples/color_patches)
- [conways_game_of_life](https://github.com/projectmesa/mesa-examples/tree/main/examples/conways_game_of_life)

The [migration guide](https://github.com/projectmesa/mesa/blob/main/docs/migration_guide.md#time-and-schedulers) might contain more information about how to move from schedulers to the AgentSet.
