### ISSUE TITLE
Update docs to remove old discussion forums

### ISSUE THREAD

**Issue by tpike3** [projectmesa/mesa#1171]
Update docs to remove google email list and google groups discussions

**Comment by rht** [comment]
As @NickleDave said in https://github.com/projectmesa/mesa/pull/1130#issuecomment-1013575842, the discussion link could probably still be stated in the readme, because there are useful discussions that people can search for.
But then again, maybe it is better to have the same questions re-answered in GH issues and discussions, so that there is only 1 place to search for them.

Hmm, I think I'm voting to just not link to the Google groups, to make it simpler.

**Comment by tpike3** [comment]
Dang, I searching in the wrong spot. I know that was out there. I will update the notes et al; 

Concur I think we just need to have one spot otherwise it is just to unwieldy.
