### ISSUE TITLE
bug: batch_run assumes model datacollector is called datacollector

### ISSUE THREAD

**Issue by tpike3** [projectmesa/mesa#1221]
**Describe the bug**
batch_run assumes user will call `DataCollector` `self.datacollector`. This is not annotated in the documentation, nor is it necessarily a requirement  

**Expected behavior**
users can name their model `DataCollector` whatever they want (e.g. `self.dc`)

**To Reproduce**
create model and name `DataCollector` anything else and then execute model with batch_run and try to retrieve the data. 

**Additional context**
Bug identified via students from the University of Mary Washington. They also had some very positive comments from their Professor
"They keep saying "wow, that's so easy! That makes it so fun!" Thanks to you and your crew for all you do."

**Comment by rht** [comment]
https://github.com/projectmesa/mesa/pull/1213#issuecomment-1080158845= will solve this issue. Although I personally prefer https://github.com/projectmesa/mesa/pull/1213#issuecomment-1080517695=.

> "They keep saying "wow, that's so easy! That makes it so fun!" Thanks to you and your crew for all you do."

This needs to be judged relative to NetLogo, because I think it's easy to do equivalent stuff in NetLogo as well.
