### ISSUE TITLE
Jupyter interface for the GUI

### ISSUE THREAD

**Issue by rht** [projectmesa/mesa#1263]
It would be great if we can use Jupyter UI widgets and components (instead of Mesa-specific UserSettableParams, ChartModule, etc), where we can have interactive simulation running inside a Jupyter session. With this, we can have easy-to-run executable examples using Binder/Colab. Currently, this is not doable? See also https://github.com/projectmesa/mesa/discussions/1259.

**Comment by jackiekazil** [comment]
100% agree. There were some attempts for Jupyter integration in the past during PyCon US sprints, but they were attempts, but not completely finished & they are old -- so not sure how helpful they are now. However I wanted to dust off these PRs to provide thoughts in how others were thinking about it... but a lot of with Jupyter/Collab has changed since these were created. 

https://github.com/projectmesa/mesa/pull/247
https://github.com/projectmesa/mesa/pull/469

**Comment by rht** [comment]
Progress update: I have simplified the non-straightforward code in #469. My prototype simply needs to be cleaned up.
![2022-05-18-065916_1195x549_scrot](https://user-images.githubusercontent.com/395821/169042043-b4799061-5701-4056-b069-195e1145cdaa.png)
