### ISSUE TITLE
Download of JS dependencies at installation time

### ISSUE THREAD

**Issue by Corvince** [projectmesa/mesa#1277]
I have noticed there have been a series of changes that make setup.py download the JS dependencies during installation. While I appreciate the effort and am sure this was done with good intentions, ***this is an absolute no-go***!

There are several serious issues with this approach:

1. The hard-coded urls in setup.py **will** eventually brake. No link stays online forever and here ressources are even fetched from several domains. This disables to possibility of installation without an internet connection (due to network errors or, firewalls, etc.). This also means that once any of these links breaks the version of mesa containing the broken link will no longer be installable. We can fix the links for future releases, but exisiting mesa releases will remain broken. We will no longer have reproducible builds, which are a cornerstone of modern library development and any scientific work. 

2. This will lead to nasty bugs. Since we no longer have control over which version of our dependencies will be installed, people will eventually end up with different versions. Since users might find out that they require e.g. bootstrap, which wasn’t available during install time, they will get some version of it and we have no way of controlling what they actually run.

3. This is a serious security concern! Not only will these links eventually break in the future, they might even be used by malicious actors to point to malware. We will then be responsible for users downloading and executing this malware. I don’t think users expect the installation of a python package to download ressources from several domains and this therefore is also a trust issue. No one should trust software unnecessarily downloading files.

Therefore these changes should be reverted asap. Unfortunately the changes have been spread out over several pull requests. I don’t know why, but this means we can’t just revert and it probably requires a bit of tedious work.

I haven’t dug into the reasoning for these changes, but if the main goal was to remove the javascript dependencies from the repo, this is a solved problem. We can use `npm` and a `package.json` file to specify our dependency versions. Then we just have to bundle the dependencies for each release and we know exactly which version of each is used. I can help with setting up the bundling if this route should be followed.

**Comment by rht** [comment]
> The hard-coded urls in setup.py will eventually brake. No link stays online forever and here ressources are even fetched from several domains.

The deps are major JS libs used by many people, and so, are unlikely to break. Also, the majority of them are from github.com.

> This disables to possibility of installation without an internet connection (due to network errors or, firewalls, etc.)

The Python dependencies (Numpy, Pandas, ...) require internet connection. I'm not sure how you find this a problem, just because these are JS files.

> Since we no longer have control over which version of our dependencies will be installed, people will eventually end up with different versions.

The versions are pinned. See https://github.com/projectmesa/mesa/blob/7c66934788fba5206600909580b3fe2c8e2a0e0f/setup.py#L69, https://github.com/projectmesa/mesa/blob/7c66934788fba5206600909580b3fe2c8e2a0e0f/mesa/visualization/templates/modular_template.html#L4. Everyone uses the exact same version with no collision.

> This is a serious security concern! Not only will these links eventually break in the future, they might even be used by malicious actors to point to malware.

See the domains: github.com, jquery.com, and cloudflare.com -- how likely will they break? If somehow the users domains are spoofed, the same thing can happen with the PyPI install URLs. If the versions are too old to be included in the CDN, then it's the more reason to upgrade. People use CDNs *all the time*.

> We can use npm and a package.json file to specify our dependency versions. Then we just have to bundle the dependencies for each release and we know exactly which version of each is used. I can help with setting up the bundling if this route should be followed.

I decided to do the current method to make it easier for users and contributors to `pip install` from the Git repo. With `npm`, you will have to update the install instruction in README.md to include `npm` (it's not a simple `pip install <git repo>` anymore), which is another extra obstacle.

**Comment by rht** [comment]
> If somehow the users domains are spoofed, the same thing can happen with the PyPI install URLs.

There is a simple mitigation method to malicious content: we can check the hash sum of the downloaded files. This is a common method used in software package distribution mirrors (though they additionally include GPG signatures). We can raise this in a separate issue.

**Comment by Corvince** [comment]
Yes, my view was more through the lens of software development. But maybe the implications for academia are even more serious. Reproducible research is a major principle underpinning the scientific method. Right now I can do `pip install Mesa==0.5` and it will just work and give me the first released version of mesa on Pypi. If I was using this version for a paper and want to reproduce the results I can just do that [1]. If we download things during installation time this won't work in the future. It takes just 1 broken link to break the installation process. We lose the ability to easily provide a reproducible environment. 

And regarding connectivity: It is not unusual for research institutions to block certain domains and/or whitelist others. This is also true e.g. for containerized developments, where python packages are provided and otherwise processes are isolated from network access. Also: `github.com` for example is not legally accessible in some countries. 

The whole idea that download links would remain online for any serious amount of time has been proven wrong just too many times. For example, we recently moved `mesa_geo` from my personal account to `projectmesa`. That means all github links to `corvince/mesa_geo` are broken. `jquery.com` is maintained by volunteers and relies on donations. Who knows how long they will be able to provide download links. `cdnjs` is a proper CDN who at least has the goal to remain stable. But it exists only for 2 years, who knows if it will be there in 5 or 10 years. 

I just don't see the benefits outweighing the risks here. Not any bit. Just so that users who install mesa from Github don't have to run a single `npm` command? They managed to install git, they will also be able to install node. 



[1] Not completely true, because of the python dependencies. Thats why we have `Pipfile.lock`.

**Comment by rht** [comment]
Let's find a common ground. @Corvince from your comment [here](https://github.com/projectmesa/mesa/issues/1277#issue-1200486568=):
> I haven’t dug into the reasoning for these changes, but if the main goal was to remove the javascript dependencies from the repo, this is a solved problem. We can use npm and a package.json file to specify our dependency versions.

At the very least, you agreed that it is better to replace the vendored dependencies with a download mechanism. But you prefer `npm`. Does this boil down to using `npm` vs CDN?

Or did you change your mind because you wanted `pip install mesa==<old version>` to work decades in the future, and so wanted the dependencies to be vendored, just like before?

**Comment by rht** [comment]
> Also, to hopefully further deepen my knowledge and up Mesa security would some approach like [bandit](https://github.com/PyCQA/bandit) be useful?

Mesa is not handling sensitive user data. It's mainly for number crunching, and so I don't think we need `bandit` (that's said, I tried running `bandit` on the repo, and found 0 issues). One scenario I could think of is to have an attacker inject unsanitary content into the user input into a remote Mesa GUI session that leads to an escalation of privilege into the host OS. But if you want to run a publicly accessible Mesa GUI session, you'd want to run the GUI session in an isolated Docker container anyway. See also #481.

**Comment by rht** [comment]
That said, I have confirmed that the current CDN method vendors all the downloaded JS files into the build output (and hence, the wheel output). This is also the case with the `npm` method.

And so, the only concern in this issue is limited to installing from Git for Mesa developers, whether `npm` is required or not.

**Comment by Corvince** [comment]
> You are applying a double standard of the content availability. How are you sure that `npm` or `pip` old packages will be available longer than the CDN-provided content? Why not vendor all the Numpy, Pandas, etc source code as well? jquery.com has been around for decades, and it has lots of mirrors, should the main one fail. As long as the JS deps versions are specified in the Mesa repo, as long as the deps are not super obscure JS libs, it is easy to find the exact version from the internet. Summary: the specifying JS deps versions is sufficient [edit: sufficient for reproducibility of the build environment]

Ah, I see your misunderstanding. Sorry for not making myself clearer. The problem is not finding the correct version somewhere on the internet (that would probably work even for obscure js deps), the problem is the breaking links. When you call `setup.py` it will cause an error and not install mesa. 

The difference to `npm` or `pip` is that those tools do not work with hard coded links. `pip` will not try to directly download  `https://files.pythonhosted.org/packages/5f/00/e840c128822e007f6f260d2aacecf6fd65f5c99cb56811a433fde09e1251/Mesa-0.9.0.tar.gz`, but it will query https://pypi.org/ to ask for a download link. Maybe the link will still work in 10 years, but if not, pip will point to another download address. Maybe pip will even be obsolete in 10 years, but something else will take over. The point is we just specify what version we need, not where to get it.  

> At the very least, you agreed that it is better to replace the vendored dependencies with a download mechanism. But you prefer `npm`. Does this boil down to using `npm` vs CDN?
> 
> Or did you change your mind because you wanted `pip install mesa==<old version>` to work decades in the future, and so wanted the dependencies to be vendored, just like before?

Again, you must have misunderstood me. As mesa is a python package and the js stuff is only used for the visualization I think vendoring is the better approach and I never changed my mind about that. Putting the js dependencies into the repo has worked so far and I don't see a strong advantage for removing it. But I don't have a strong opinion there and I don't oppose removing them. But in that case they should be vendored at release time, not added during installation time. That is, before packaging up a new mesa release, bundle the dependencies and provide them in the release package.

> That said, I have confirmed that the current CDN method vendors all the downloaded JS files into the build output (and hence, the wheel output). 

This is finally some good news. It means if mesa really decides to keep the "CDN method" I can sleep a little bit better, since releases will only be half-broken in the future (although it will still be a shame to have broken source releases)

**Comment by Corvince** [comment]
[This is a clarification post, not important for the actual discussion]

> If so, how does `npm` solve this, if only Python packages are provided?

As said above I would vendor the js deps anyway. And for github installs you are right that npm must be available, but installing the python modules and the npm packages are 2 separate steps and could be handled as such (at worst the frontend would not work, but that would not affect the rest of mesa) 

> 
> > That means all github links to corvince/mesa_geo are broken.
> 
> Not true. You should try it yourself, github.com/Corvince/mesa-geo redirects to github.com/projectmesa/mesa-geo

Yes, but a redirect is a different server response. Thats normally no problem for a GET request, but in this specific case only as long as I don't create a new `mesa_geo` repo :upside_down_face: 


>  Does this boil down to using `npm` vs CDN?

I am reallly not sure what you mean here. `npm` _is_ utilizing CDNs, whereas some of your links are _not_ CDNs (jquery.com, github). So this question doesn't seem to make a lot of sense!?

**Comment by rht** [comment]
If the major CDNs will be gone in 10 years, people wouldn't want to use them.

> The difference to npm or pip is that those tools do not work with hard coded links.  ...
> Maybe the link will still work in 10 years, but if not, pip will point to another download address. Maybe pip will even be obsolete in 10 years, but something else will take over. The point is we just specify what version we need, not where to get it.

You are stating as if it is not recoverable in 10 years. Again, the JS versions are pinned in the setup.py.
In case your remaining complaint is the old source installation:
In the unlikely case when the links are broken, there is a workaround for `pip install -e git+https://github.com/projectmesa/mesa#egg=mesa@v0.5`: just pre-download the JS files from elsewhere.

I already said this myself, the pinned versions in setup.py are enough for reproducibility. In 10 years from now, if some links are broken, it's not that the package is completely uninstallable.

>  but installing the python modules and the npm packages are 2 separate steps and could be handled as such (at worst the frontend would not work, but that would not affect the rest of mesa)

The JS files are "caches" download during setup.py invocation and can be downloaded via other means in advance, separately.

> Yes, but a redirect is a different server response. Thats normally no problem for a GET request, but in this specific case only as long as I don't create a new mesa_geo repo upside_down_face

GitHub has provided the redirect, doesn't this already solve your *earlier concern* about broken links? I'm not sure why you are looking for more faults. It's your courtesy not to create a new mesa-geo repo for trolling purpose.

> I am reallly not sure what you mean here. npm is utilizing CDNs, whereas some of your links are not CDNs (jquery.com, github). So this question doesn't seem to make a lot of sense!?

You can read https://releases.jquery.com/; it says "jQuery CDN".
As with github.com, fair point (because e.g. Julia packages installation used to be slow for some users because they downloaded from github.com, but they have since used a package registry server), but I'm saying CDN as a convenient concise umbrella term. If you want, CDNs and github.com. Aside from the definition clarification, github.com releases links have been available for a long time. See https://github.com/jekyll/jekyll/releases?page=11 (earliest release in June 14 2013).

**Comment by rht** [comment]
> I think vendoring is the better approach and I never changed my mind about that.

You said in https://github.com/projectmesa/mesa/issues/1277#issue-1200486568=

> We can use npm and a package.json file to specify our dependency versions. 

And so, you changed your mind about wanting to use `npm`, that now you are back to preferring vendoring.

**Comment by tpike3** [comment]
@rht and @Corvince I am making comments from the cheap seats here, but it seems this topic is very hotly debated. Ideally I would have found some type of peer reviewed research but I so far I really fond online articles that cover many of the same arguments. 

Just for reference as my references as my confidence in their reputably is low here are some I found illuminating: 
[Should I vendor](http://codeengineered.com/blog/2015/go-should-i-vendor/)
[Vendoring Dependencies](https://www.dermitch.de/post/offline-dependencies-js-yarn-python/endoring)

Are there better references? In the end it seems like we are in the trade-off space here, each approach has strengths and weaknesses but there is not a universal solution (like the No Free Lunch or Arrow's theorem) . 

I also saw git submodules as maybe an alternative but it does not seem to get around any of the core issues raised here. 

My additional impression is this is very much a challenge of JavaScript where code can be as specific as `bootstrap slider`. 

I am running short on time this morning, but I will try and summarize the pros and cons of each approach for your review, just to try and comprehensively summarize the trade-off.

**Comment by rht** [comment]
> [Should I vendor](http://codeengineered.com/blog/2015/go-should-i-vendor/)

The article on Golang vendoring is outdated. It was long written before [`go mod`](https://go.dev/ref/mod) was a thing. Note: Go Modules is Golang's own take on dependency management. Golang developers no longer vendor nowadays.

> [Vendoring Dependencies](https://www.dermitch.de/post/offline-dependencies-js-yarn-python/endoring)

HTTP 404 for me. Can't read the article.

If I were to summarize my position:

I am optimizing for:
1. ease of installation for *most people* (`pip install git+...`; no `npm`) that applies the whole time from today onward
2. ease of update compared to vendoring, and hence can be frequently done
3. no need to attribute in a THIRDPARTY file (except in the release wheel); we are lucky that the JS libraries vendored so far are not copylefted that would require Mesa's license to be copyleft as well
4. no accumulated older JS files in the Git repo, which results in smaller repo size
This is essentially my summary for #1195, i.e. the original thread.

At the cost of having to find the JS files elsewhere should the:
1. unlikely situation where jquery.com/github.com somehow stop providing files
2. unlikely situation where I want to run a dusty 10-year-old code in year 2032
The chance of the 2 unlikely events happening is even far lower.

I'm applying the [80/20 rule](https://en.wikipedia.org/wiki/Pareto_principle) that we should optimize for the common 80% use case instead of the uncommon 20% use case. Though it is actually closer to 95/5 or higher here.

**Comment by Corvince** [comment]
Thank you @tpike3 for jumping in and @rht for your very nice summary. 

I agree 95% with your 4 optimization points. The only difference I see is that _most_ people install through `pip install` (i.e. not from GitHub). I think those that _do_ install from github should be considered knowledgeable enough to run an additional `npm` command. I see GitHub primarily as a development platform, not a distribution method (apart from GitHub releases, but this doesn't provide the source code).

However, I want to optimize for two additional points:
  5. Reproducible builds that only require `pip` to work, for ease of reproducible science and to stay within the limits of the Python world.
  6. Not exposing users to unnecessary security risks. 

While I agree that the last point is very unlikely to happen, it is better to be safe than sorry. But it is in the 20% range of the 80/20 rule. Reproducible builds would however make it to the top of my optimization list.

And to say this again: Of course with pinned dependencies builds will remain reproducible, but the cost of reproduction will be unnecessarily high.

It really is not the question _if_ the links break, but rather _when_ and under what circumstances do they break.

We can fix this now before problems arise or after. It just breaks years of software development experience and best practices. I am sure you won't find any major python package that downloads _anything_ during install time (from a fixed url).

**Comment by rht** [comment]
> 6. Not exposing users to unnecessary security risks.

I answered in https://github.com/projectmesa/mesa/issues/1277#issuecomment-1095706318= that you can specify hash and do checksum on the download, and so is a solved problem.

> Reproducible builds would however make it to the top of my optimization list.

The CDNs I use are highly available. The wheels already contain vendored JS files with my method, and so I'm not sacrificing this off.

> And to say this again: Of course with pinned dependencies builds will remain reproducible, but the cost of reproduction will be unnecessarily high.

The cost sure is relatively high to manually find the JS files, but not prohibitively high. But again, this is an uncommon use case.

> It just breaks years of software development experience and best practices. I am sure you won't find any major python package that downloads anything during install time (from a fixed url).

Citation needed. Because their cases are different. You need to find projects with similar needs and use case as Mesa for a fair comparison. Also, it's not just some unknownwebsite.com URL, it's jquery.com/github.com that a lot of people rely on.

**Comment by Corvince** [comment]
> > 6. Not exposing users to unnecessary security risks.
> 
> I answered in [#1277 (comment)](https://github.com/projectmesa/mesa/issues/1277#issuecomment-1095706318) that you can specify hash and do checksum on the download, and so is a solved problem.

No, this is not a solved problem, this is a solvable problem. Do you really want to manually look up and copy-paste checksums for every dependency upgrade? And/or expect others to do so? 
 
> 
> > Reproducible builds would however make it to the top of my optimization list.
> 
> The CDNs I use are highly available. 

Fast and reliable, yes, future proof - only time will tell (this is not one of the main goals of CDNs). I already explained how easy it is break github links. Another way of breaking a github link is to remove/exchange releases. Jquery.com will only remain online as long as jquery.com is alive. 
If this really will remain the way to go I would at least prefer to download everything from the same CDN - single point of failure and such (and cdnjs is probably a very good choice)

> The wheels already contain vendored JS files with my method, and so I'm not sacrificing this off.

As I said earlier this is really good news and means most people will be relatively safe. But since you seem to favor installs from Github this is obviously not the case there. 

> Citation needed. Because their cases are different. You need to find projects with similar needs and use case as Mesa for a fair comparison. Also, it's not just some unknownwebsite.com URL, it's jquery.com/github.com that a lot of people rely on.

The need to (theoretically) download files/ non-python dependencies during installation is very common.

**Comment by rht** [comment]
There is a fourth potential solution: to use Fanstatic or similar tool to package the JS files within Python packages. See #1195.
Fanstatic no longer maintains their wrapped Bootstrap D3.js, etc, but we can pick up from where they left off.
This way, most people who want to install from Git won't need to set up `npm`. The preparation that requires `npm` will be ~~swept under the rug~~done by these separate wrapper Python packages. The downside is that this is an extra work for Mesa maintainers. :/

**Comment by Corvince** [comment]
> Looking forward to examples you can provide. Again, the use case is that the package needs to be easily installable.

No problemo, but before I prepare such a list can you define "easily installable" and why that is important for mesa? 

> This way, most people who want to install from Git won't need to set up `npm`

May I ask what are your concerns regarding setting up `npm`? This only affects people who already managed to set up git, they should be able to set up `npm` as well, no? If this really boils down to not wanting to use `npm` I must understand something wrong about the implications of using `npm`.

**Comment by rht** [comment]
> No problemo, but before I prepare such a list can you define "easily installable" and why that is important for mesa?

Easily installable: one scenario is that if I have a repo with requirements.txt, if I want to use a particular commit of Mesa repo, perhaps in my GH Actions CI for testing, I should be able to do this:
```
...
pytorch>=1.11
git+https://github.com/projectmesa/mesa@7c66934788fba5206600909580b3fe2c8e2a0e0f#egg=mesa-git
...
```
or `@main`. Otherwise, we break people's assumption on the `pip` installation method being self-contained as with most Python packages.

Regarding my other concern for `npm` and `node`, it's overkill considering that `node` is not even used for running the server, and that the only feature that is used with `npm` is downloading the packages.

In addition to https://github.com/projectmesa/mesa/issues/1277#issuecomment-1098069334=, there is a fifth option, which is to separate the visualization module to a separate Git repo, `mesa-visualization` (and we require them with `mesa-visualization==0.1.0`), and we can use `npm` there, because people who want to develop on the JS code are expecting to use `npm`.

**Comment by rht** [comment]
Though the CI env may not be a good representative example, because I can just do `apt-get install nodejs`, just like in Cython, where I need to have `gcc` installed.

**Comment by Corvince** [comment]
> Otherwise, we break people's assumption on the `pip` installation method being self-contained as with most Python packages.

[citation needed]  :wink: 

Of course I agree that `pip install mesa` is expected to be self-contained. But that remains true. But `pip install git+`? I would have expected that most people don't even know that this is possible. I have to ask about the use case here again. As you said yourself CI is not a good example. 

I mean I agree that `pip install -e git+` will become more cumbersome and I haven't thought about that initially. But what about the 80/20 rule? If this is indeed very common than this becomes a very important point, but is it? I mean `pip install git+github` will work, it will just not install the frontend. 

Installing specific revisions will have to change from (pseude code of course)
```
pip install -e git+github...@revision
```
to 
``` 
git clone mesa
cd mesa
pip install -e git+file...@revision
npm build
``` 

Again, this is indeed a bit more complicated, but still possible. Is that really the common use case we should optimize for?


> Regarding my other concern for `npm` and `node`, it's overkill considering that `node` is not even used for running the server, and that the only feature that is used with `npm` is downloading the packages.
> 

I always thought the main use case for cloning the repository is for development work. And if that development work is done for the main parts of mesa you don't have to install npm, you just can't use the server in that case. And if the development targets the frontend you need `npm` anyways to run `eslint` and `prettier` (of course you could also do the formatting by hand, but this is very error prone). 

I know we have the install instructions to install from github quite on top of our readme. But this used to be a workaround for irregular mesa releases and because people kept running into not being able to run the examples, due to unreleased changes.

Again, I challenge you to find any python package that is "easily installable" with non-python dependencies.

**Comment by rht** [comment]
I'm not sure of your position. In https://github.com/projectmesa/mesa/issues/1277#issuecomment-1097431940=, I summarized that you initially preferred `npm`, and then switched to preferring vendoring. Now it looks like you're back with `npm` again.

So your point is that `pip install git+` is not common. This is common for most Python requirements.txt content, and if you want proof, see https://github.com/search?q=filename%3Arequirements.txt+%22git%2B%22&type=code.
Whether the Mesa community use this a lot, I cannot prove, but I do have one data point: you can see that people are using the `RandomActivationByType` scheduler (not yet released) that is from the main branch: https://github.com/projectmesa/mesa/discussions/1191.

> Again, I challenge you to find any python package that is "easily installable" with non-python dependencies.

Sure, Mesa is easily installable when the JS files were vendored, and still is. The non-Python dependencies in this case are minified JS, which don't require `node` to run.

For frontend development, I agree that `eslint` and `prettier` are needed, but this is not >80% of the dev case either. You can check the PRs that most of them touched mainly the Python code only.

Once again, I have stated this solution
> In addition to https://github.com/projectmesa/mesa/issues/1277#issuecomment-1098069334, there is a fifth option, which is to separate the visualization module to a separate Git repo, mesa-visualization (and we require them with mesa-visualization==0.1.0), and we can use npm there, because people who want to develop on the JS code are expecting to use npm.

It's not like the JS download code is long and buggy. The download code https://github.com/projectmesa/mesa/blob/7c66934788fba5206600909580b3fe2c8e2a0e0f/setup.py#L37-L62 is ~30 LOC. Will get a bit longer with the hash checksum, but this already saves setup time.

**Comment by tpike3** [comment]
As there is too many specifics to quote I am **going to try** and summarize key debate areas and add to the dev session Saturday: 

1. **Ease to install and use**: The main feedback we have gotten has been from Universities, TU Delft, U. Mary Washington, GMU, Delaware Futures [part of University of Delaware), plus many one offs mostly from Europe. From this our main use cases appear to be academics many of whom are just starting. In this vein our *competition* is not other python packages its Netlogo and possibly Agents.jl. I think ease of installation is absolutely paramount, we lose that we lose our user base. 

2. **Secure**: Critical we have to have security. If there are easy ways to do this (e.g. checksums etc) we should do it. I would also advocate that Mesa should employ tools available through GitHub and others and we should have a discussion (similar to this one) about the best approaches for that.

3. **Reproducible**: Piling on point 1, academia is in a reproducibility crisis so we should take steps to make it easily reproducible and speaking naively it may be better to do this locally (e.g. you get an image of the build you used) instead of globally.

The larger issue this speaks to is what is Mesa's larger vision. 

My view, which at this time we cannot resource, is a rich and varied ecosystem that allows for three different archetypes. 

- **new academic**: who needs the easy install and a rich ecosystem of data and behaviors to explore phenomenon
- **app developer user**:  I think this speaks to much of what @Corvince (please correct me if I am wrong...great to have you in the discussion again!) was arguing for where we have Mesa visualization separate and assume deeper developer knowledge and where models can be used for decision making like @aiwhoo
- **advanced researcher**: Harder to use Mesa that has needs rigor and significant computing power, requires projects like Mesa HPC (we have a meeting with a potentially interested postdoc). 

I think this would be good for a larger strategy discussion, but as this conversation is a lot about trade-offs where there is no *answer* discussing the larger visions now is unavoidable. 

At this point I would advocate we focus on the **new academic** archetype as that is our user base but a larger view of the direction we are headed is critical to those micro decisions.

**Comment by Corvince** [comment]
> So your point is that `pip install git+` is not common. This is common for most Python requirements.txt content, and if you want proof, see https://github.com/search?q=filename%3Arequirements.txt+%22git%2B%22&type=code. 

Sorry, but this is getting ridiculous. Your search results in 82,912 results. But there are 2,619,132 requirements.txt files on GitHub (https://github.com/search?l=&p=99&q=filename%3Arequirements.txt&ref=advsearch&type=Code). How is ~3% a prove that this is common for most requirement files?  


> > Again, I challenge you to find any python package that is "easily installable" with non-python dependencies.
> 
> Sure, Mesa is easily installable when the JS files were vendored, and still is. The non-Python dependencies in this case are minified JS, which don't require `node` to run.

Sorry I meant to find any python package that is "easily installable" with non-python dependencies that downloads these dependencies  (or anything else for that matter) during install time (like I previously asked in https://github.com/projectmesa/mesa/issues/1277#issuecomment-1097989714)

> 
> For frontend development, I agree that `eslint` and `prettier` are needed, but this is not >80% of the dev case either. You can check the PRs that most of them touched mainly the Python code only.
> 
> Once again, I have stated this solution
> 

Please try to read my comments more carefully. As I said you don't need to install npm if you only touch the Python code. 


> I'm not sure of your position. In [#1277 (comment)](https://github.com/projectmesa/mesa/issues/1277#issuecomment-1097431940), I summarized that you initially preferred `npm`, and then switched to preferring vendoring. 

No, in [#1277 (comment)](https://github.com/projectmesa/mesa/issues/1277#issuecomment-1097431940) you took a sentence of me out of context and tried to make it look like I am switching positions.

My original statement 
> if the main goal was to remove the javascript dependencies from the repo, this is a solved problem. We can use npm and a package.json file to specify our dependency versions. 

And my clarification (https://github.com/projectmesa/mesa/issues/1277#issuecomment-1097156710)

>As mesa is a python package and the js stuff is only used for the visualization I think vendoring is the better approach and I never changed my mind about that. Putting the js dependencies into the repo has worked so far and I don't see a strong advantage for removing it. But I don't have a strong opinion there and I don't oppose removing them. But in that case they should be vendored at release time, not added during installation time. That is, before packaging up a new mesa release, bundle the dependencies and provide them in the release package.

I still and have always preferred vendoring the JS dependencies directly (like before), but I see the advantages of removing them from the repo __and in that case__ would use `npm`. I really don't know how else I can say that. What exactly remains unclear for you about my position?

I feel like this discussion isn't going anywhere at the moment. Just quoting ourselves is a bit pointless. Let's see if others will join in

**Comment by rht** [comment]
@tpike3 that's a great, concrete contextualization.

(I was actually quoting myself (from https://github.com/projectmesa/mesa/issues/1277#issuecomment-1098574547=) on the solution to separate the visualization code to another Git repo, which I think is a viable middle ground)

**Comment by Corvince** [comment]
> > No, this is not a solved problem, this is a solvable problem. Do you really want to manually look up and copy-paste checksums for every dependency upgrade? And/or expect others to do so?
> 
> No, it is automatic. I haven't added the hash sum in the current implementation, but it is quick to add. The principle is the same as
> 
> ```
> <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
> ```
> 

Forgot that one. Again, please try to read my comments carefully. There is no way to do that automatically for your approach __for dependency upgrades__. Whereas with with npm this is just `npm install bootstrap@version` (hash sums are then saved in a `package.lock` file

**Comment by Corvince** [comment]
> @tpike3 that's a great, concrete contextualization.
> 
> (I was actually quoting myself (from [#1277 (comment)](https://github.com/projectmesa/mesa/issues/1277#issuecomment-1098574547)) on the solution to separate the visualization code to another Git repo, which I think is a viable middle ground)

This is something I also had in mind for quite some time and think is a good idea. This could also solve some of the examples problems. I would imagine a `mesa` meta-package, which installs `mesa-core`, `mesa-visualization` and `mesa-examples` as separate packages. This way `mesa-core` could be relatively stable and sufficient to install if the other two are not needed. But this should of course be discussed in a separate thread.

**Comment by rht** [comment]
> Sorry, but this is getting ridiculous. Your search results in 82,912 results. But there are 2,619,132 requirements.txt files on GitHub (https://github.com/search?l=&p=99&q=filename%3Arequirements.txt&ref=advsearch&type=Code). How is ~3% a prove that this is common for most requirement files?

Fair point.

> Please try to read my comments more carefully. As I said you don't need to install npm if you only touch the Python code.

Disagree. If I am writing a new example (which generally has a server.py) / a new agent template, etc, I need to be able to run the visualization server to test.

> I still and have always preferred vendoring the JS dependencies directly (like before), but I see the advantages of removing them from the repo and in that case would use npm. I really don't know how else I can say that. What exactly remains unclear for you about my position?

That's why. Your statement was unclear. Is it vendoring directly, or use `npm`? I can't even tell.

**Comment by rht** [comment]
> > > No, this is not a solved problem, this is a solvable problem. Do you really want to manually look up and copy-paste checksums for every dependency upgrade? And/or expect others to do so?
> > 
> > 
> > No, it is automatic. I haven't added the hash sum in the current implementation, but it is quick to add. The principle is the same as
> > ```
> > <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
> > ```
> 
> Forgot that one. Again, please try to read my comments carefully. There is no way to do that automatically for your approach **for dependency upgrades**. Whereas with with npm this is just `npm install bootstrap@version` (hash sums are then saved in a `package.lock` file

Well, my point is that users don't have to manually check the hashsum of the downloaded JS files. I just need to specify the hashsum in the setup.py. What's so difficult about updating the hashsum to setup.py during upgrades?

**Comment by Corvince** [comment]
> Disagree. If I am writing a new example (which generally has a server.py) / a new agent template, etc, I need to be able to run the visualization server to test.

How does this fit with your statement

>  this is not >80% of the dev case either. You can check the PRs that most of them touched mainly the Python code only.

How many of the PRs touch the visualization side of the examples?



> 
> > I still and have always preferred vendoring the JS dependencies directly (like before), but I see the advantages of removing them from the repo and in that case would use npm. I really don't know how else I can say that. What exactly remains unclear for you about my position?
> 
> That's why. Your statement was unclear. Is it vendoring directly, or use `npm`? I can't even tell.

I prefer directly putting *.js inside the repo. My impression was that there is a consensus to remove them from the repo. This is not my preference. But I am totally fine with that. I won't oppose in any way to remove them. If we remove them I would strongly advise to use `npm`. The dependencies should then be vendored via `npm` for every release on PyPI. 
Sorry if it is still not clear, I am not a native speaker. 

> Well, my point is that users don't have to manually check the hashsum of the downloaded JS files. 

That is true, but I never challenged that. No one ever said that users need to check hashsums

> What's so difficult about updating the hashsum to setup.py during upgrades?

This

> The downside is that this is an extra work for Mesa maintainers. :/

**Comment by tpike3** [comment]
@Corvince and @rht.... This has been fascinating and for an academic like myself amazing to read and try to tangentially research. However, I think to your points.... we also feel like the conversation has culminated.

So I am going to close this thread and as this deals with big issues and some specific dev needs I am going to put the critical points (not attributed) over to the dev session thread with some decisions the team has to make.
