### ISSUE TITLE
Feature Request: Agent DataCollection Can't Handle Different Attributes in ActivationByType 

### ISSUE THREAD

**Issue by tpike3** [projectmesa/mesa#1419]
**Describe the Feature**
Receive attribute error when running an agent reporter through datacollector when using RandomActivationByType 

**Desired behavior**
I can collect against different attributes based on agent type

**To Reproduce**
Create a model with different agent types and attributes and try to collect against that agent attribute

**Additional context**
Feature would need to update at line 170 of datacollection.py `agent_records = map(get_reports, model.schedule.agents)`

**Comment by jackiekazil** [comment]
@tpike3 I am unable to recreate the bug -- it looks like sugarscape_cg uses `RandomActivationByType`. Can you add it to that example & recreate it?

**Comment by tpike3** [comment]
If you use this colab you will get the error https://github.com/edgeofchaos42/ComplexityExplorer/blob/main/Session_18_Data_Collector_agent.ipynb Attached is the landscape you will need to load into your google drive. or update the `sugar_distribution = ` line

Per the dev session this morning I should be able to add a custom function to filter out non-traders or at least return None, but so far unsuccessful on that code. 


[sugar-map.txt](https://github.com/projectmesa/mesa/files/9639657/sugar-map.txt)

**Comment by rht** [comment]
I think a temporary workaround is to put the trade partners in the model reporter instead.
```
lambda m: {k: list(a.trade_partners) for k, a in m.schedule.agents_by_type[Trader].items()}
```

I used `list()` to copy the `a.trade_partners`.

**Comment by EwoutH** [comment]
This is indeed a (in my opinion big) limitation. I wrote a proof of concept implementation for it in https://github.com/projectmesa/mesa/pull/1142, and used it in a personal project. If anyone ones to built on it, feel free to use it in any way!

**Comment by rht** [comment]
```
agent_reporters = {Cat: {"Weight": "weight", "Size": "size"}, Dog: {"Weight": "weight"}}
```

While this looks more concise for `RandomActivationByType`, it is a pattern that only works for this scheduler. We can't just modify `DataCollector` to expect more different types of schedulers. `DataCollector` will become more bloated. And this is not much more concise than the workaround I specified in my earlier comment. The lack of the feature is not a blocker in @tpike3's situation.

Either:
- Create a `DataCollectorRABT` (shorthand for `DataCollectorRandomActivationByType`) class that handles types for agent collector
- Tell people to put their type-specific data in the model collector, like in https://github.com/projectmesa/mesa/issues/1419#issuecomment-1257158578. Put the guide in in best-practices.rst

We should look at how other ABM libraries choose their trade-off here.

**Comment by EwoutH** [comment]
Could we create a new switch for the DataCollector, `multiple_agent_types`, for example, which is `False` by default but can be set to `True` if you want to collect data from multiple agent types? That way it's still contained to a single class, which can reduce the maintenance effort.

**Comment by rht** [comment]
The maintenance effort is about the same with `DataCollectorRandomActivationByType`, since it will inherit from `DataCollector`, and only `_record_agents` needs to be replaced to handle agents by type. Adding an extra switch and if clause inside `DataCollector` doesn't scale, because what if there is a scheduler with 2-level type hierarchy (`Dict[str, Dict[str, Dict[int, Agent]]]`, see [Multi-level Mesa](https://github.com/tpike3/multilevel_mesa)? The switch and the if's keep growing.

**Comment by EwoutH** [comment]
That's a good point.

Would you be interested in creating an (draft) implementation?

**Comment by rht** [comment]
My plate is rather full right now.

**Comment by EwoutH** [comment]
Thanks for the honest reply, let's discuss at the next development meeting how we can move this project forward.

**Comment by EwoutH** [comment]
What if you would restructure the [`DataCollector`](https://github.com/projectmesa/mesa/blob/af23b8bc854ec85235642a549ad1924bd19aa4a3/mesa/datacollection.py#L45) in such way that it's split in an agent-data and model-data part?

Maybe a `DataCollector` superclass with a `ModelDataCollector` and a `AgentDataCollector` subclasses? In that case the `ModelDataCollector` always expects a single model as input, and a `AgentDataCollector` a single agent type. If you want to collect data for more that one agent type, you simply call the `AgentDataCollector` multiple times.

Many of the code is now duplicate such as `_new_model_reporter` and `_new_agent_reporter`, so why not split those? And everything that's shared can sit in the `DataCollector` superclass.

**Comment by jacob-thrackle** [comment]
I'm also running into this issue with respect to the agent attributes. After reading through the code, I wonder if it would be possible to just pass a specific `schedule` to the `DataCollector` constructor instead of assuming ([hard-coding](https://github.com/projectmesa/mesa/blob/659b00a0c547864f3a4359ac8f8e50359703d631/mesa/datacollection.py#L168)) that there exists an object in the model called `schedule`. That would seem to limit the bloat of `DataCollector` and remove one of the implicit assumptions in the class.

So something like this in the `Model`:
```python
self.datacollector = mesa.DataCollector(
    schedule = self.schedule, # arbitrary schedule with an .agents attribute that returns a list of agents
    agent_reporters = {...},
    model_reporters = {...}
)
```

**Comment by rht** [comment]
> Maybe a DataCollector superclass with a ModelDataCollector and a AgentDataCollector subclasses?
> ... 
> If you want to collect data for more that one agent type, you simply call the AgentDataCollector multiple times.

This definitely could provide ingredients for people who want to build their own data collector class. But I don't see it to be cleaner than just inheriting from the current `DataCollector` class and modifying the method you want to change as needed.

I think for now, for trading Sugarscape use case, we should implement the solution within the examples folder. Then wait for a while for it to become a part of the library.

**Comment by rht** [comment]
@jacob-thrackle your solution could work. Though we also want to make sure the >80% of the use case stays simple and convenient, where the scheduler is assigned to the model attribute `schedule` anyway. So that users don't have to specify the scheduler object every time.

**Comment by jacob-thrackle** [comment]
Absolutely. I started hacking around with it last night but the following section makes it difficult because of the string type for `model.schedule.steps` in `prefix` (line 158):
https://github.com/projectmesa/mesa/blob/373637ed28566f0c35832bfd5b51d44eae8739ab/mesa/datacollection.py#L156-L166

If I'm understanding the code correctly, the condition at line 157 is only `True` if all the `rep_funcs` are `partial` which is only true if the `reporter` is a `str`:
https://github.com/projectmesa/mesa/blob/373637ed28566f0c35832bfd5b51d44eae8739ab/mesa/datacollection.py#L137-L141

So having a reporter be a lambda or some other arbitrary function would make this not true and evaluate the `else` statement at line 161. I assume that it is done this way so that `get_reports = attrgetter(*prefix + attributes)` is really fast if the reporters are just attributes of the agents but this gain is nullified once you use anything other than a string in the reporter dictionary in the `DataCollector` itself. Since the `DataCollector.collect` method is typically only called once per model-step, and unless there are a huge number of agents in which one is only interested in getting attributes, it may be worthwhile to consider removing the condition and expression in lines 157-160 and just using the function at 163. 

Using the function has the added advantage of calling `self._getattr()` which has a default value of `None`, meaning that attributes which do not exist return `None` instead of throwing an `AttributeError`. The code in lines 158-160 never call `self._getattr()` and just use the `attribute_name` which is passed to `attrgetter()`.

This is all to say that I was able to make my suggestion work by simply removing lines 157-161, only using the function `get_reports` at line 163 with some minor adjustments, including a condition for backwards compatibility where the scheduler is assigned to the model attribute `schedule`:
```python
if self.schedule:
    schedule = self.schedule # new behavior
else:
    schedule = model.schedule # old behavior, self.schedule defaults to None in the constructor
```

Thoughts?

**Comment by rht** [comment]
That L157-161 seems to be written by @Corvince in https://github.com/projectmesa/mesa/commit/aaa4c545fbaaeb7408c74148e96510421ea243fa. The original commit contains this comment for the `attrgetter`
```python
# Fast path if all reporters are attribute collecters
```
but had since been removed in the subsequent iterations.

But the original PR that did the specialization of the code when all the reporters are string-based, is #576. #575 contains some benchmark results

**Comment by Corvince** [comment]
Thanks for digging that up @rht 

And yes, @jacob-thrackle you understood exactly right how it works. 
Basically, attrgetter gives the best possible performance, but only works if we have only string collectors.
This is a pure performance optimization. But, as you figured out, does not allow a default value.

Is is probably better to give up a tiny bit of performance by using getattr instead of attrgetter to have default values

**Comment by woolgathering** [comment]
@Corvince Cool, I opened a PR from my personal account. Let me know when you guys get around to reviewing it and what changes, if any, you'd like me to make.
