### ISSUE TITLE
Small typo in tutorial code

### ISSUE THREAD

**Issue by StevenHaveman** [projectmesa/mesa#1467]
**Describe the bug**
In the example code in the tutorial, in the "Adding Space" section (https://mesa.readthedocs.io/en/latest/tutorials/intro_tutorial.html)
There is a code snippet like this:
```
    def __init__(self, N, width, height):
        self.num_agents = N
        self.grid = mesa.space.MultiGrid(width, height, True)
        self.schedule = RandomActivation(self)
```

**Expected behavior**
I expected for the last line
`self.schedule = mesa.time.RandomActivation(self)`
Otherwise it throws an error (at least for me)

**Additional context**
Thanks for the project and great tutorial, look forward to work with it more!

**Comment by Tortar** [comment]
I opened a PR so that to fix the tutorial, yes you're right it was wrong :-)

**Comment by rht** [comment]
I grepped the rest of the doc/ to see if there are remaining issues of the same nature. The good news is there are none. But I found that [docs/overview.rst](https://github.com/projectmesa/mesa/blob/0c23349a5c65102aef327558b1b82a04c4045b6b/docs/overview.rst) still uses the older way of using Mesa namespace.

```python
from mesa.time import RandomActivation
...
RandomActivation(...)
```

instead of
```python
import mesa
...
mesa.time.RandomActivation(...)
```

I will fix this.
