### ISSUE TITLE
Not building from source

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#174]
When trying to build and install Mesa from source, something -- one of the dependencies, I think -- is failing. Fun times, not least because this means that the documentation isn't building either.

To replicate:
- Download / clone the repo
- Make a new virtualenv
- Go into downloaded code directory, and `python setup.py install`
- Wait for failure.

**Comment by dmasad** [comment]
When I manually pip install the requirements (numpy, pandas, tornado) and *then* ``python setup.py install`` it works.

**Comment by dmasad** [comment]
[Log for failed RTD build](https://readthedocs.org/projects/mesa/builds/3463792/)

**Comment by paultopia** [comment]
After a little bit of poking around, it looks like this is a known bit of scipy pissiness---it basically refuses to go and fetch numpy on its own, apparently other dependencies as well, and just decides to puke instead.  See this sklearn issue https://github.com/scikit-learn/scikit-learn/issues/4164 and this SO http://stackoverflow.com/questions/11114225/installing-scipy-and-numpy-using-pip  -- as I read the log (hopefully I'm not misreading it) it looks like the install is trying to build scipy before actually installing numpy... 

(Hi there... sniffing around-I quite like this mesa concept--might try to make a couple of contribs... though probably not to this issue, because if the scipy people can't figure out a good way to handle this I sure can't!)

**Comment by dmasad** [comment]
Good to know! Looks like There are ways around it now (and the RTD issue was separate after all), so not a high priority.
