### ISSUE TITLE
JupyterViz: the default grid space drawer doesn't scale to large size

### ISSUE THREAD

**Issue by rht** [projectmesa/mesa#1741]
**Describe the bug**

Here is Schelling space for 60x60:
![2023-07-24-102909_468x350_scrot](https://github.com/projectmesa/mesa/assets/395821/0949b124-dfeb-48ff-9205-4d242e99c833)

**Expected behavior**

Should either scale down the circle marker size automatically, or scale up the figure size automatically.

**Comment by rlskoeser** [comment]
I vote for scaling up the figure size (which I'm understanding as allocating more space for the agent space figure on the page). Not sure how you would determine the threshold for this - would it have to be user configurable, or could a certain grid size automatically require 3/4 of the width, full width?

**Comment by rht** [comment]
I think we should do both simultaneously.

**Comment by ankitk50** [comment]
I started looking into this-- some upfront ideas here:

1.  If we need to make the figure scalable , I would be better if we make the plots one per row (so that the scaling can be done to the whole screen).

2. I think it would be better to implement it as a test feature that can be enabled via a checkbox. 

3. The agents size looks straight forward to scale based on number of agents. I look into ways to scale the figure. `GridDraggable` in solara looks like a promising feature in this regard.

**Comment by rht** [comment]
There shouldn't be upfront customization from the user unless necessary. This should behave like how LaTeX renders documents, where people focus on the content of the writing, not the layout. Automatically deciding when to use the entire row or not, scaling down marker size, increasing figure size, should be the library's responsibility.

**Comment by ankitk50** [comment]
Sure, I have open a draft PR #1820.
