### ISSUE TITLE
DataCollector and lambdas

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#175]
Currently the default DataCollector API encourages the use of lambdas to define the model- and agent reporters. This is nice and readable, and doesn't require subclassing the DataCollector for each model. However, it turns out that lambdas are not pickle-able. This means that model objects using DataCollectors can't easily be serialized, which creates problems for checkpointing, model storage, and parallelization (since [ipyparallel](http://ipyparallel.readthedocs.org/en/latest/) uses pickle to send objects between engines.

One solution is just clarifying in the documentation that code needs to be written slightly differently for these cases. Another is figuring out another way to do reporters in DataCollector.

**Comment by datnamer** [comment]
The dill library can serialize lambdas IIRC.

**Comment by dmasad** [comment]
I've tried dill as well. It can be made to do it, but with a couple caveats: mostly that it has to be by reference (``dill.dump(model, f, byref=True)``) which means that the original model classes needs to exist in the interpreter when the model is read back in. External classes in dill seem to generate some weird behaviors, which are (may be?) under development. See [this StackOverflow discussion](http://stackoverflow.com/questions/32363312/why-dill-dumps-external-classes-by-reference-no-matter-what).

**Comment by max-orhai** [comment]
We could rewrite the docstring to encourage the use of named functions rather than lambdas. Seems a little clunky to me though. Also, I'd love to avoid extra dependencies like `dill`.

Maybe we could make use of `getattr` and `@property` instead? So the reporter value would be a string, and instead of calling `reporter(model)` for a model reporter, we'd just use `getattr(model, reporter)`. The reporters dicts would then look like `{"agent_count": "schedule.get_agent_count"}` and the `get_agent_count` method would get a `@property` decorator.

What do you think?

**Comment by Corvince** [comment]
fixed by #589
