### ISSUE TITLE
Allow displaying mesa visualizations inline in jupyter notebooks

### ISSUE THREAD

**Issue by smacleod** [projectmesa/mesa#246]
It would be nice to run the Model visualizations inside of a notebook.

**Comment by jackiekazil** [comment]
Last update on this -- https://github.com/projectmesa/mesa/pull/469

**Comment by guy1ziv2** [comment]
Any progress on this? I am trying to use Mesa on Calaboratory as it is easy for undergraduate teaching (clean VM with python without any fuss). I can easily run Mesa examples, except anything related to visualization...

**Comment by dmasad** [comment]
Unfortunately this line of work seems to have stalled out somewhat. 

One option you might want to check out is [HoloViews](http://holoviews.org/index.html), which enables more interactive visualizations in the notebook. The HoloViews team put together a nice example of Mesa + HoloViews a few years ago (https://nbviewer.jupyter.org/gist/jlstevens/9c7835e4e21c5d844ded) -- I think the API has changed a bit since then, but that might help get you started.

**Comment by rht** [comment]
Solved by https://github.com/projectmesa/mesa-examples/pull/44. It's not yet in core Mesa because it's still experimental. But installation guide is added in https://github.com/projectmesa/mesa-examples/pull/45.
