### ISSUE TITLE
Should 'examples' not be covered by pep enforcement? Discuss

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#270]
TODO: 
* Remove examples from pep enforcement. 
* Clean up any issues that resolve from the issue

---------------------
This line of the travis file: https://github.com/projectmesa/mesa/blob/master/.travis.yml#L17
... ignores 'examples', which led to this clean up: #269

This doesn't make sense to me. Is there a reason why this is there? 
Discuss!

**Comment by lowcloudnine** [comment]
Concur, it doesn't need to be there.  I would also recommend removing the docs ignore as the only py file in there is the conf.py and since the project is maturing it is doubtful you'll ever need to do a sphinx-quickstart again so just fix the 48 pep8 errors be done.  In the entire project running a default flake8 with no ignores or excludes there are 139 errors.  If you would like 'I volunteer' to fix them but I won't be done until sometime next week, i.e. I'll be doing them over the weekend.  Then you can remove the ignores and excludes from .travis.yml.

**Comment by jackiekazil** [comment]
I updated the ticket to turn this into a task for someone to pick up during scipy
