### ISSUE TITLE
BatchRunner's behaviour

### ISSUE THREAD

**Issue by dadaromeo** [projectmesa/mesa#342]
I was trying to reproduce the *Credit Risk* example in [Agent-Based Modeling and Simulation](http://link.springer.com/book/10.1057/9781137453648) when I noticed that the output of the batch running were different to the output of the running in the browser.  [Here](https://gist.github.com/dadaromeo/3f37ffb883e9c6b0793e684e7bf0c0a1) is where I describe the problem.

**Comment by dmasad** [comment]
Thanks for your feedback! It looks like the confusion is in the naming of the ``iterations`` argument. I definitely think it could have a better name. Maybe something like ``n_runs``?

I think it's important to keep the ``max_steps`` argument there, though, since some models may not have end conditions, or may not always reach them.

**Comment by dadaromeo** [comment]
> It looks like the confusion is in the naming of the `iterations` argument.

My confusion isn't much in the name of the `iterations` argument but in the meaning of it, because of the `max_steps` argument. If the `iterations` argument is the number of runs of a model, then a model will run at most `iterations` or `n_runs` (if you prefer) if `self.running = True` without  the `max_steps` argument. But with the `max_steps` argument, the model will run at most `iterations * max_steps` if `self.running = True`.

> ...since some models may not have end conditions, or may not always reach them.

I think the number of iterations or runs is the "ultimate" end condition.

**Comment by dmasad** [comment]
I think I see the confusion. ``iterations`` is the number of different instantiations of the model for each parameter combination -- it doesn't affect the number of steps each instantiation is run for. 

With your example, if ``param_vals = {"option": ["dec", "inc"], "amount": [1,2]}`` and ``iterations=1``, there will be four model instantiations, one for each combination: ("dec", 1), ("dec", 2), ("inc," 1) and ("inc", 2). Each model will then run for ``max_steps`` steps. When you set ``iterations=5``, there will be 20 model instantiations, five for each of the four combinations above -- and each one of those instantiations will still run for ``max_steps`` steps.

**Comment by dadaromeo** [comment]
Oh, I see. In the dataframe below is  the output of the dummy model I described earlier with `iterations = 1` and `max_steps = 5`.

|   | Run | amount | option | total |
|---|-----|--------|--------|-------|
| 0 | 1   | 2      | dec    | -20   |
| 1 | 2   | 1      | inc    | 10    |
| 2 | 0   | 1      | dec    | -10   |
| 3 | 3   | 2      | inc    | 20    |

First of all, we see that the `Run` field is actually the field of the model's indexes (4 in this case, as you pointed out in your previous comment) and not the field of the model's steps as one might expect. Second, only the last value of the model variable `total` is recorded, not at each step as one might expect (if of course, this is not the expected behavior). With part of what you said in your previous comment, one is expecting something like this:

|     | Run | amount | option | total |
|-----|-----|--------|--------|-------|
| 0   | 0   | 2      | dec    | -4    |
| 1   | 0   | 1      | inc    | 2     |
| 2   | 0   | 1      | dec    | -2    |
| 3   | 0   | 2      | inc    | 4     |
| 4   | 1   | 2      | dec    | -8    |
| 5   | 1   | 1      | inc    | 4     |
| 6   | 1   | 1      | dec    | -4    |
| 7   | 1   | 2      | inc    | 8     |
| ... | ... | ...    | ...    | ...   |
| 16  | 4   | 2      | dec    | -20   |
| 17  | 4   | 1      | inc    | 10    |
| 18  | 4   | 1      | dec    | -10   |
| 19  | 4   | 2      | inc    | 20    |

Clearly, with this output, we see that at each step, the batch runner instantiates the 4 models, run them, record the model's variable at each step and moves to the next step.

> ... with `iterations=1` there will be four model instantiations, ... When you set `iterations=5`, there will be 20 model instantiations, ...

20! I thought the number of model instantiated was proportional to the number of combinations of the parameter values. What is the purpose of having such many models instances?

Thus, my initial trouble wasn't due to the `max_steps` parameter as I was thinking but, now that I can see, with the `iterations` parameter.

**Comment by dmasad** [comment]
In Mesa terms, a *step* is a time-tick of the model, within a single instantiation. A *run* is a model being instantiated and then going through some number of steps. BatchRunner generates some number of runs, and collects the reporter values at the end of each run. Recording each step of each instantiation would probably be a good thing to add, though.

The number of runs the BatchRunner generates is proportional to the number of combinations. That's why the baseline in the example is four runs -- one for each parameter combination. Setting `iterations=5` means that BatchRunner will generate five runs for each of those combinations, for 4x5=20 runs in total. 

The reason for having this option is that since models usually have a random element, it's good practice to run a model multiple times even with the same parameters to make sure that you're seeing typical behavior.

**Comment by dadaromeo** [comment]
OK, I got it now. Thanks for clearing that up.

**Comment by dmasad** [comment]
Glad I could help, and thanks for highlighting the parts you found unclear!
