### ISSUE TITLE
Simple Semantics

### ISSUE THREAD

**Issue by Corvince** [projectmesa/mesa#351]
Dear all,

I just want to present some ideas and semantics that I would find more intuitive for exploring mesa and it's capabilities. Also, setting some default values could help to rapidly prototype new models. 

[An example notebook detailing my approach and ideas can be found here
](https://gist.github.com/Corvince/a409f57357c3fce171b4374a4f8df24e#file-simpler-semantics-ipynb)
I don't think most of the changes matter too much when working with "real", complex models, but maybe some of the ideas can be used for the mesa package to make it easier for newcomers. 

Putting the changes together and writing the notebook was basically a big exercise for me to familiarize myself with mesa, so please be honest with your criticism. I won't think I "wasted" time if no one likes this or there are good reasons not to do it this way. 

Waiting for your comments
Corvince

**Comment by dmasad** [comment]
I like this idea. We've talked about a heavier-duty version of the same thing (e.g. the idea for ['MesaLogo'](https://github.com/projectmesa/mesa/issues/173)) but haven't done much to move it forward.

I think including something like this would be great. A few ideas for modifications / enhancements:

* Instead of the simple semantics being added to the base Model class, should there be a SimpleModel class or something with defaults?
* If so, should there be string-based defaults (e.g. instead of `grid=space.MultiGrid(...)`, have it be `grid="MultiGrid`, width=10, ....`)?
* Likewise, a SimpleAgent class, with build-in behaviors (e.g. `move_left`, `move_random`), possibly aware of the kind of grid it lives on?

Though now that I type that out, I wonder whether that's a separate effort, and that something like what you propose here is an intermediate useful feature.

**Comment by Corvince** [comment]
Closed as (discussion) dead
