### ISSUE TITLE
Python 3.4 build breaking... 

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#353]
See https://travis-ci.org/projectmesa/mesa
& https://travis-ci.org/projectmesa/mesa/jobs/196418735

` ImportError: No module named 'six'` 

not sure why this is a problem now & only with the 3.4 build.

**Comment by Corvince** [comment]
I know this sounds a bit esoteric, but installing six before installing the requirements solves this bug. (From [here](https://stackoverflow.com/questions/42549931/travis-ci-build-on-python3-4-six-urllib-wont-install))

You can see my travis logs here:
https://travis-ci.org/Corvince/mesa

Note that I first put six at the top of the requirements list, but this didn't help. You probably only have to change the .travis.yml (The above log includes both changes)

Still the logs from 3.4 and 3.5 are quite different and something odd is going on for 3.4. 
But it builds... and maybe someone can look into this deeper

**Comment by njvrzm** [comment]
This is the result of a change introduced in setuptools version 34. Breaking like this is "expected behavior", if you're not using the latest version of pip, according to the maintainers 😬.  We can get around it with @Corvince's fix or I think by requesting an older version of setuptools in the requirements.txt, which will also help folks to install Mesa if they're not completely up to date. I'm testing that fix now and will update here in a moment.

**Comment by njvrzm** [comment]
Downgrading setuptools (from 34 to <34) works. I've pushed the fix to master and will rerun the failing travis builds.

**Comment by njvrzm** [comment]
All green now :)
