### ISSUE TITLE
Agents in Flocker example always move to bottom right

### ISSUE THREAD

**Issue by sowasser** [projectmesa/mesa#358]
Hi,

I'm looking into using the Mesa Flocker model as a jumping-off point for research on the collective behaviour of mackerel, and I've played around quite a bit with the code, but I can't figure out why the boids always end up flocking towards the lower, righthand corner.

Does anyone have an explanation for this behaviour, or could point me to the place in the code that creates it? I'm new to Python so it's quite possible I'm missing something.

Thank you!

**Comment by dmasad** [comment]
It looks like the problem is in the `cohere` method in the `Boid` class. Right now, it just returns the center of all the nearby boids, where actually it should be the vector from the current boid towards the center. It shouldn't be too hard to fix -- you're welcome to take a shot at it if you want; otherwise, I'll try to fix it soon!

**Comment by sowassermann** [comment]
I'll take a stab at it, thank you!

**Comment by sowassermann** [comment]
So I've done my best to re-write the `cohere` method to return the vector towards the center. The behavior in the visualization has changed somewhat, but they still always end up in the same orientation, appearing from the upper-left corner, with now with one branch heading to the upper-right, and one to the lower-left. Here's the code I changed.

```python
    def cohere(self, neighbors):
        """
        Add the vector toward the center of mass of the local neighbors to the
        position of each agent to return a new vector towards neighbors.
        """
        my_pos = np.array(self.pos)
        coh_vector = np.array([0.0, 0.0])
        for neighbor in neighbors:
            center = np.array(neighbor.pos) / len(neighbors)
            coh_vector += [my_pos[0] - center[0],
                           my_pos[1] - center[1]]
        return coh_vector
```

I'd greatly appreciate any more hints or help with the code. Thanks again!

**Comment by jharrison** [comment]
After a cursory glance at boid.py, I think I see the problem. The heading is initialized as follows:

`self.heading = np.random.random(2)`

I can't be certain this is the case because the docs.scipy.org is dead right now, but I'm guessing that random() returns positive values, possibly between 0 and 1. This means heading will only be positive, i.e., rightward and downward. Assuming random() returns values between 0 and 1, you probably want to do this instead:

`self.heading = np.random.random(2) - 0.5`

**Comment by sowassermann** [comment]
The heading doesn't seem to be an issue; as is, it is returning positive and negative values (between 0 and 1). What I think might be the issue is `speed` in the `Boid` class. It's scalar - distance to move per step and when it's switched from 5 to -5 (for example) the boids switch to always heading to the upper-right corner. Not sure how to fix this! Code as is: 

```python
    def __init__(self, unique_id, model, pos, speed=5, heading=None,
                 vision=5, separation=1):
        """
        Create a new Boid flocker agent. Args:
            unique_id: Unique agent identifyer.
            pos: Starting position
            speed: Distance to move per step.
            heading: numpy vector for the Boid's direction of movement.
            vision: Radius to look around for nearby Boids.
            separation: Minimum distance to maintain from other Boids.
        """
        super().__init__(unique_id, model)
        self.pos = pos
        self.speed = speed
```

**Comment by sowassermann** [comment]
Hi again,

So I've managed to remove speed and have, for the moment, compensated by changing `match_heading` to match velocities (magnitude of the non-normalized heading vector). However, `vision` is also causing the agents to move to the lower-right. If I insert a negative number, they all head to the upper-right. I'd appreciate help with this as it seems to involve the `get_neighbors` function.

**Comment by dmasad** [comment]
I've played with it some more, and I've found something that seems to solve the problem (though it causes another one). The key thing is to normalize the `cohere`, `separate`, and  `match_heading` vectors before adding them together.  (See the code here https://github.com/projectmesa/mesa/blob/flockers.358/examples/Flockers/flockers/boid.py)

This does produce many small flocks moving in different directions. The one remaining weird behavior is that larger flocks start moving slower, and seem to start almost hovering around a central point. I haven't analyzed it in detail, but it seems to happen when smaller flocks with almost opposite directions meet. Reducing the `vision` parameter seems to reduce that issue, largely by preventing such large flocks from forming to begin with.

**Comment by sowassermann** [comment]
Fascinating!

I decided to calculated center of mass slightly differently. Instead of taking the average of the neighbors' positions, I used the SciPy `ndimage.measurements.center_of_mass` function. Now, I might have done this wrong, but it's now producing the opposite behavior as before; all boids head to the upper-right. My `cohere` code is below, the rest is the same as the update to boid.py.

```Python
    def cohere(self, neighbors):
        """
        Return the vector toward the center of mass of the local neighbors.
        """
        from scipy import ndimage
        vec = np.array([0.0, 0.0])
        their_pos = [neighbor.pos for neighbor in neighbors]
        their_pos = np.asarray(their_pos)
        center = ndimage.measurements.center_of_mass(their_pos)
        vec += np.subtract(center, self.pos)  # both are tuples
        if np.linalg.norm(vec) > 0:
            return vec / np.linalg.norm(vec)
        else:
            return vec
```

**Comment by njvrzm** [comment]
Late to the game here, but this is a good catch! There are a number of problems, some minor and some serious, with the math in the model as is. For instance, the neighbor heading matching part does nothing at all! Also, the `cohere` and `separate` functions are confused by the borders of the space.

I've started working on a fix and will make a PR soon, and update here when it's available for discussion.

**Comment by jackiekazil** [comment]
@njvrzm -- I know you are working on a could of things... is this still in progress? (just wanted to update the ticket.) :-D

**Comment by njvrzm** [comment]
It is! PR #378.

**Comment by sowasser** [comment]
Thank you, @njvrzm. I've played around with your new code and looks good to my non-expert eyes.

**Comment by jackiekazil** [comment]
This has been fixed!
