### ISSUE TITLE
Multiple generations of agents

### ISSUE THREAD

**Issue by reynoldsnlp** [projectmesa/mesa#361]
I would like to use mesa for a project I am working on, but I am not sure how best to approach it. It will likely lead to new contributions to the base code, or at least an extension.

The idea is to have adult agents and child agents, add network connections between agents, children learn from adults, adults "die", children mature into adults, and then a new generation of child agents is created, and the process iterates again. At first, I thought that this would work best as a new kind of Scheduler, because it manages which agents are activated when. However, it also seems to be a special case of a BatchRunner, but where each new iteration is dependent on the previous iteration's output.

As for data collection in my case, the most important metrics would involve the final states of agents after each iteration.

Before I make a first draft, does anyone have any suggestions for the best way to build this?

**Comment by Corvince** [comment]
Hi there,

interesting idea! Regarding your question, I think the easiest way to have generations is to simply have a generation attribute for each agent in your model. Depending on if self.generation == "child" or "adult" they can then learn, die or mature (interesting order you picked there ;) )
Classically this would be tied to an "age" attribute, but could also be implemented otherwise.

Another idea, if the actions of children and adults are very different and you clearly want to separate them, you could have two agent-types and simply transfer the attributes of the Child into a new Adult once the Child matures (and in model-terms kill the Child agent).

But maybe I am missing an important point why your model would need a new Scheduler or BatchRunner. You should ask yourself "what is time in this model?" and "what is a scheduled step in this model?". Maybe your ideas can be simplified to use the existing Schedulers?

**Comment by nlpcall** [comment]
Thanks, I'll see what I come up with.

**Comment by djmitche** [comment]
I think everything you need for this is already present in Mesa.  Here's a little model I pulled together.  Its behavior isn't very interesting, but has the necessary attributes.

```python
import random
import itertools
from mesa import Model, Agent
from mesa.time import RandomActivation

unique_ids = itertools.count()

P_CHILD = 0.4
P_DEATH = 0.2

class Organism(Agent):
    def __init__(self, model, generation):
        super().__init__(next(unique_ids), model)
        self.generation = generation
        self.age = 0

    def step(self):
        if random.random() < P_CHILD:
            self.model.schedule.add(Organism(self.model, self.generation + 1))

        if random.random() < P_DEATH * self.age:
            self.model.schedule.remove(self)

        self.age += 1

class Population(Model):
    def __init__(self, seed=None):
        super().__init__(seed)
        self.schedule = RandomActivation(self)

        progenitor = Organism(self, 0)
        self.schedule.add(progenitor)

    def step(self):
        self.schedule.step()

model = Population()
for i in range(30):
    model.step()
    print(sorted([a.generation for a in model.schedule.agents]))
```

As @Corvince mentioned, you probably do not want to use different classes for Chlidren and Adults, as an instance can't change its class -- a child would have to always be a child.  If you wanted different behavior, you could use a conditional based on `self.age`.

The magic of the evolving population is in the `self.model.schedule.add` and `self.model.schedule.remove` calls, which add and remove agents from the population.
