### ISSUE TITLE
Get agent vars dataframe slow/silently crashes when number of agents is high

### ISSUE THREAD

**Issue by larsasp** [projectmesa/mesa#384]
I want to run my model with 100K agents, and save to a csv so I can do some data analysis on them. However, the get_agents_vars_dataframe function is either very slow (left cooking over night, still busy by lunch the day after) or it has silently crashed. Has anyone encountered this before, or have a suggested solution?

**Comment by dmasad** [comment]
That's good to know! I think the problem is that `DataCollector` stores everything in memory using core Python data structures, which really isn't optimal when dealing with large volumes of data. 

The long-term solution is to rewrite DataCollector to at least have the option of using something more efficient. The short-term hack (if you're still trying to resolve this problem) might be to write the results out in smaller batches during the model run, as opposed to waiting to the end.

Is your model code available online (or are you willing to share it)? It would be useful to have a test case to see where Mesa is failing now, and be able to check against to see if it's been fixed.

**Comment by larsasp** [comment]
Hi, 
Yes we decided to make our own collector to just store the events we needed, so it was not too difficult to work around actually. The model is on my github, however it is an utter mess at the moment, but I will type it up nicely soon.
Thanks,
Lars
