### ISSUE TITLE
error launching Flocker

### ISSUE THREAD

**Issue by smartinsightsfromdata** [projectmesa/mesa#395]
I've Anaconda with python 3.6 & Mesa 0.8.1

I launch Flocker's run.py and I get this error:
```
Flockers e$ python run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from flockers.server import server
  File "/Users/e/Dropbox/devlib/notebooks/mesa-master/examples/Flockers/flockers/server.py", line 20, in <module>
    server = ModularServer(BoidModel, [boid_canvas], "Boids", model_params)
  File "/Users/e/anaconda3/lib/python3.6/site-packages/mesa/visualization/ModularVisualization.py", line 287, in __init__
    self.reset_model()
  File "/Users/e/anaconda3/lib/python3.6/site-packages/mesa/visualization/ModularVisualization.py", line 313, in reset_model
    self.model = self.model_cls(**model_params)
TypeError: __init__() got an unexpected keyword argument 'N'
```

**Comment by jackiekazil** [comment]
Trying to recreate this issue now....

**Comment by jackiekazil** [comment]
@smartinsightsfromdata -- a bandaid for you is to comment out this line https://github.com/projectmesa/mesa/blob/master/examples/Flockers/flockers/server.py#L12 & try running again. 

@dmasad, when I started to look into this issue, it looks like it is related to this change -https://github.com/projectmesa/mesa/commit/2ca1de70147ea36a93b912a196ed3a64c7d10b4d#diff-3221e8b9ab8c2773dd44dd9fea582ff0... N is set on model init to 100. Then there "N" under model params. As stated above, if you remove the "N", then it "fixes" the problem. Making something work versus properly fixings it are 2 different.  Because you more familiar with these changes ---  If this is an easy fix / problem for you to identify, I would like to punt to you, otherwise, I will look into this further. Let me know.

**Comment by rht** [comment]
I think it's a variable naming issue, where `N` should have been `population` (https://github.com/projectmesa/mesa/blob/master/examples/Flockers/flockers/model.py#L25 (I didn't use a hashed link here :/)) instead.
