### ISSUE TITLE
Question on SingleGrid placing/moving agents

### ISSUE THREAD

**Issue by zhiyzuo** [projectmesa/mesa#408]
Thank you for this great tool! 

I am trying to use `SingleGrid` but does not understand three things.

(i) Is there any difference between `move_agent`, `place_agent`, and `position_agent`?

(ii) If I use `SimultaneousActivation` to move agents, and two agents want to move to the same cell, how do the scheduler or the model decide which one to go? 

For the second question, it seems like I would get an error complaining 

> Not an empty cell!

for one of the agents that want to move to the same spot with another agents.

How can I set the scheduler to work in the way that ties are broken randomly and those agents not selected to move will stay put?

(iii) It seems like when I use `SingleGrid`, I need to have an `agent.advance()` method. I could not find much information in the doc. What is it?

Thank you in advance!

**Comment by Corvince** [comment]
Dear zhiyzuo,

please remember that Github is mainly used for bug reporting, in the future you should best ask your question [here](https://groups.google.com/forum/#!forum/projectmesa).

(i) `place_agent`places an Agent as a specified position, whereas `position_agent` allows you to assign the position randomly and should be used when initially positioning agents. 
`move_agent` only works for agents that are already on the grid and, well, moves the agent from one cell to another, freeing up the old position

(ii) Thats one of the pitfalls when using `SimultaneousActivation`. There is no way to know for the scheduler what the expected behavior for your model is. You want to break ties randomly and one agent should stay, but someone else might not want the decision to be randomly and the other agent should go somewhere else. Therefore you have to redefine `SimultaneousActivation` to suit your needs. 
But, just a hint, if it is just about the moving of agents your expected behavior is exactly like `RandomActivation`

(iii) Thats a limitation of `SimultaneousActivation`, not `SingleGrid`. The expected behavior is that the `step` function does the calculations based on the current state (e.g. decide where to move) and than `advance` executes the actions (e.g. move). Otherwise the current state would change constantly.

Hope this helps

**Comment by zhiyzuo** [comment]
Thank you! I will close this and move to google forum!
