### ISSUE TITLE
mesa automatically installed to python 2.7 folder instead of python 3.4 folder

### ISSUE THREAD

**Issue by kevintoy** [projectmesa/mesa#442]
Hi,

I had some trouble configuring my ubuntu system and eventually was able to install mesa. However, all the relevant packages seemed to be installed to the python 2.7 folder instead of python 3.4 folder and as a result I can't import mesa in python 3.4. I was able to import mesa in python 2.7 but due to the syntax differences the example code would run properly. Could someone provide me with some advice regarding how to direct mesa to be installed in such a way to be compatible with python 3.x?

Thanks,

Kevin

**Comment by dmasad** [comment]
Hi Kevin,
I think that if you have both Python 2 and 3 installed, and you want to use the global package folders (as opposed to virtual environments), you need to install packages with `pip3` (see e.g. [here](https://askubuntu.com/questions/412178/how-to-install-pip-for-python-3-in-ubuntu-12-04-lts)). 

Another alternative is to create a Python 3 [virtual environment ](https://realpython.com/blog/python/python-virtual-environments-a-primer/), and install Mesa inside of it. That's what I'd recommend -- especially since Mesa does update often enough that you want to make it easy for you to either keep a static version associated with a specific project, and to reinstall it if you want access to newer features.

**Comment by jackiekazil** [comment]
@kevintoy Looks like @dmasad chimed in on this. Please let us know if you are still having difficulties.
