### ISSUE TITLE
Mesa running problem

### ISSUE THREAD

**Issue by sachithnalaka** [projectmesa/mesa#471]
When I try to execute examples, I get following errors.
`python run.py `

TypeError: super() takes at least 1 argument (0 given)

if I use python3

ImportError: No module named 'mesa'

**Comment by JamesArruda** [comment]
Did you pip install mesa, or download it from the repo here?

If you downloaded it, you may need to install it still.

**Comment by sachithnalaka** [comment]
I used git repo.. Yes, I tried `pip install mesa`

Requirement already satisfied: mesa in /usr/local/lib/python2.7/dist-packages

**Comment by jackiekazil** [comment]
You have to run Mesa in Python3. It won't run in Python2... this is because the community is dropping support for python2, so we never incorporated it. 

you are getting the import error, because 'mesa' is not on your python path. 

if you `pip install mesa`, you should be okay as long as you are installing it into your python3 environment and not your python2 environment. If you `git clone`, you will need to add it manually to your python path. 

The easiest way to this is via virtual environments and virtualenvwrapper's command `add2virtualenv`. 

Let me know if that helps or if you have more questions because something is unclear.

**Comment by sachithnalaka** [comment]
I upgrade pip to pip3 and then installed mesa using `sudo pip3 install mesa`

Its working now. Thanks.

**Comment by ICRanger** [comment]
I get a requirement to add a password? What should I do...

**Comment by jackiekazil** [comment]
@ICRanger that is the password for your laptop. That is your system asking you -- do you want to run this as 'sudo' if so, you need to authorize with your password. Search for "sudo" on the internet to learn more.
