### ISSUE TITLE
Color patches takes a long time to load

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#498]
When you hit "reset" to load the color patches example, it takes a long time to load.
Not sure why. As a result, I thought it was broken.

To recreate... 
```
cd examples/color_patches
python run.py
```

Wait for patches to load when browser window pops up. 
OR hit reset and wait for color patches to load.

This is what it should look something like...
<img width="407" alt="screen shot 2018-04-01 at 10 03 33 pm" src="https://user-images.githubusercontent.com/166734/38180194-95c2acb0-35f8-11e8-8c1b-8bd7a6d25098.png">

**Comment by bintoy** [comment]
I was dealing with the same problem earlier this year and found out that the canvas values were being used instead of the grid values when starting up the server:

https://github.com/projectmesa/mesa/blob/d376920146ca0ec422286cb8434d86b74e64b2fa/examples/color_patches/color_patches/server.py#L65

{"width": canvas_width, "height": canvas_height} should be changed to {"width": grid_rows, "height": grid_cols}

**Comment by jackiekazil** [comment]
@bintoy ty for suggestion. There is a PR now.
