### ISSUE TITLE
ChartModule unable to plot Series which is a tuple

### ISSUE THREAD

**Issue by samhitad** [projectmesa/mesa#507]
Hi,

I am running an ABM where  one of the  model-level series is a tuple as the function call returns a tuple. I attempted to run a visualization with plotting for said model-level series but the plotting doesn't budge from zero. I took a look at ChartVizualization.py and I can see why this is happening (it's being caught the except statement) but I don't know how to fix it especially since I am not sure what is using the render function.
I tried to fix this by having the DataCollector assign each element of the tuple to a different model-level series but the way DataCollection.py is written, I am not sure how to work that. 
Any guidance that lets me (a) plot a tuple using ChartModule or (b) let me assign each value of a tuple (resulting from a function call) to different model-level series would be much appreciated!
I am quite new to GitHub and I am not sure of the protocol here but I am not posting the code here as it's rather involved and maybe detracts from the main issue of plotting tuples but let me know if providing code helps.

Thanks in advance!

**Comment by jackiekazil** [comment]
@samhitad -- can you share your code -- the lines that are causing the issues? It makes it easier to trouble shoot.

**Comment by samhitad** [comment]
Hi,

Sorry for the very late response. I was trying to recreate one of the user submitted models on NetLogo in Mesa. I ran into trouble with the visualisation as one of the label variables for the chart was a tuple. You can find the code [here.](https://github.com/samhitad/Artificial-Financial-Market/blob/Replication/Wonky%20Artificial%20Financial%20Markets%20Replication.ipynb) I fixed it by writing two different function instead of one so the function call was no longer returning a tuple. However I still think it's worth looking into plotting tuples as sometimes it may not be possible/desirable to work around having a function call return a tuple.
 Also I have noticed that there are not many examples on financial markets in Mesa, I'll be more than happy to clean up what I have done here so that an example on financial markets is available for the Mesa community (with permission from the original netlogo user as appropriate). Again I am not really a frequent github user so do let me know if I am not using the forum as intended.

Best,
Samhita

**Comment by jackiekazil** [comment]
@samhitad -- Welcome! 
This is the right forum, but it helps to create small distinct tickets for tracking and discussion, others good things are lost. In addition to that, tickets are cheap. :-) 

I might be wrong, but right now, I see two tickets -- tuple chart request and financial model
Can you open the following (you don't have to use my wording, this is only for guidance)?

## Allow for charts to accept tuple
Right now charts do X. (link to example, so people reading can be lazy and respond quickly) 
That is frustrating because of Y. 
It would be awesome if it would do this...
```
code example of what is should look like goes here
```

## Add financial model to Mesa Examples
I wrote the following example model from Netlogo -- (link to code). There is no financial market example in Mesa. Should I submit a PR?

**Comment by jackiekazil** [comment]
@samhitad -- I am closing this ticket since since it seems like you figured out your issue. I look forward to you submitting future tickets!
