### ISSUE TITLE
Issues with Running Examples

### ISSUE THREAD

**Issue by justinhastings** [projectmesa/mesa#552]
Whenever I try to run the command 'mesa run' I get an error message saying that the 'mesa' command is not found. I also get an error message whenever I try to run the command 'python run.py'.. I have attached both error messages to this ticket. 
![mesa error](https://user-images.githubusercontent.com/31353236/41242797-77afc4e4-6d6e-11e8-8be4-468df040466f.PNG)

**Comment by jackiekazil** [comment]
@justinhastings ... i documented the mesa run thing in #553. The other issue is your version of tornado. If you look at the current requirements.txt, it locks it down to a specific version, because the latest version raises that error. 

I am going to close this ticket for now. Please submit another if you run into any more issue OR reopen this one if you need more help.
