### ISSUE TITLE
[Feature request] remove agents during Scheduler.step()

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [projectmesa/mesa#583]
**What's the problem this feature will solve?**
E.g. the step of the RandomActivation:
```
def step(self):
 """ Execute the step of all the agents, one at a time. """
    agent_keys = list(self._agents.keys())
    for agent_key in agent_keys:
        self._agents[agent_key].step()
    self.steps += 1
    self.time += 1
```
If lets say agent 1 'kills' agent 2, and this agent gets removed from _agents, we get the error that self._agents does not contain agent 2. This forces us to keep track of agents whether they are alive or not.

**Describe the solution you'd like**
Either use a generator to generate the keys, or do check in-place if the agent still exists. I would propose using a generator, something like this:
```
def mesa_keys(agents, shuffled=False):
    agent_keys = list(agents)
    if shuffled:
        random.shuffle(agent_keys)

    for key in agent_keys:
        if key in agents:
            yield key
```
Now you can simply replace the 
```
agent_keys = list(self._agents.keys())
for agent_key in agent_keys:
```
with
```
for agent_key in mesa_keys(agents, shuffled=False):
```

Would you guys be interested in something like this?

**Comment by Corvince** [comment]
Good spot, that should definitely be possible! 

I think a PR would be very welcome, but a small observation: The `agents` argument actually requires the agent_keys, right? Or, I would write inside `mesa_keys`:

    agent_keys = list(agents.keys())

 And mesa_keys might not be the best name, but I couldn't come up with something better ;)

Oh and maybe you could also modify to yield the agents directly and not just the keys? I don't know why the current implementation doesn't do this already, since we just want to call the agents' `step` function, right?

**Comment by Corvince** [comment]
Thanks!

Re 1) Ah, yes of course! I was confused because normally the 'agents' variable refers to a list of actual agents. Sorry, but for the sake of clarity please use `.keys()`

And I can't think of a logical assumption that agents should still be activated even though they are killed/removed from the scheduler. Of course, this shouldn't happen in the case of a simultaneous activation. 
In all other cases I would leave it to the modeler to create a list of agents that will be removed and only remove them after `schedule.step()` is called. That should be trivial to implement. 

Otherwise, I really wouldn't expect agents to do anything after they are killed/removed from the scheduler. But I agree that someone else should also have a look into this.
