### ISSUE TITLE
Von Neumann incorrect during visualisation

### ISSUE THREAD

**Issue by LXH605** [projectmesa/mesa#603]
I'm writing code for a Forest Fire model and am using the Von Neumann neighborhood (through moore = False). I have a visualisation to show the spread of the fire and when I run it the Von Neumann neighborhood seems to use the diagonals instead of left/right/top/bottom.
I'm also using SimultaneousActivation to avoid the fire spreading more than it should in each step but there are still issues with this and some trees burn out before appearing to be lit.

Does anybody have experience with these issues/know how to resolve them?

I can't link to my code as it is being used for a project so will flag up on the plagiarism checker if I do!

**Comment by jackiekazil** [comment]
RE: I can't link to my code as it is being used for a project so will flag up on the plagiarism checker if I do! 
^^ I have never heard that before and people share code all the time. If that is truly a worry, please let me know of a case where that has happened with code in a setting like this. I am willing to reach out to the company personally to try to help resolve that, because that would be endemic of a big problem. There is just too much code that is shared casually when fixing bugs like this. 

Can you do a video recording or create a gif of the action?

**Comment by WouterVrielink** [comment]
Did you properly set the radius? [When using radius > 1 it will do diagonals.](http://mathworld.wolfram.com/vonNeumannNeighborhood.html)
