### ISSUE TITLE
TypeError: 'module' object is not callable - Money Model Advanced Tutorial

### ISSUE THREAD

**Issue by BiscoMan** [projectmesa/mesa#628]
Hello! 
First of all thank you for creating Mesa, it's really impressive and it will be a major help for my master thesis. 

I am trying to do the money exchange advanced tutorial, but when I run the server I got the following error message "TypeError: 'module' object is not callable". I know what the error means but I can't fix it. 

I imported the model as "from model import MoneyModel" in server.py, but it won't fix it. I will leave the MoneyModel and Server code attached.

Ps: I am new to Python, so probably this is a noob question. If it's the case sorry in advance.

Thank you again.

[MoneyModel.zip](https://github.com/projectmesa/mesa/files/2794380/MoneyModel.zip)

**Comment by martin-c-harvey** [comment]
I am new to Python too. I think your problem is that 'module' is not a .py file (you can import packages, which are directories too, see https://chrisyeh96.github.io/2017/08/08/definitive-guide-python-imports.html). 

I got your code running straight away with: 
`from MoneyModel import MoneyModel`

Note that "When a module is imported, Python runs all of the code in the module file." so the MoneyModel class knows what a MoneyAgent is.

**Comment by Corvince** [comment]
Thanks for solving this Martin!

In the future, consider uploading your code as a GitHub gist, as not everyone is comfortable with opening unknown zips (also more difficult on mobile)
