### ISSUE TITLE
Master needs a flake8 clean up

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#636]
Something messy got merged in from a previous PR and is causing other PRs to fail -- ie #634 
```
$ flake8 . --ignore=F403,E501,E123,E128,W504 --exclude=docs,build
./tests/test_lifespan.py:61:16: F632 use ==/!= to compare str, bytes, and int literals
The command "flake8 . --ignore=F403,E501,E123,E128,W504 --exclude=docs,build" exited with 1.
```

**Comment by Corvince** [comment]
Sorry forgot to drop a note about this! This was already fixed in fae3e7f504982ac5a89bf9336805f025704eb41c 
I already noticed this error some days ago and I think was actually introduced by a newer version of flake8. Since the fix was only to change 
`if np.random.binomial(1, 0.1) is not 0`
to 
`if np.random.binomial(1, 0.1) != 0`
I pushed this to master directly. The failing PRs were/are outdated (rerun travis fixes them). Sorry for the confusion!
