### ISSUE TITLE
Create an example that demos StagedActivation

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#657]
**What's the problem this feature will solve?**
There is no example which demos StagedActivation. So, it is difficult to do a user test on it. 

**Describe the solution you'd like**
I would like an example (maybe one translated from Netlogo) that demonstrates StagedActivation in the time module.

**Comment by sd235634** [comment]
agree,I'm looking forward to see examples using StagedActivation,thanks

**Comment by EwoutH** [comment]
Since we're moving away from schedulers, this is no longer needed. You can do this now with AgentSet behavior:

```Python
class SomeModel(Model)
    ...
    def step(self):
        """
        Perform the model step in two stages:
        - First, all cells assume their next state (whether they will be dead or alive)
        - Then, all cells change state to their next state
        """
        self.agents.do("determine_state")
        self.agents.do("assume_state")

```
See as examples:
- [hex_snowflake](https://github.com/projectmesa/mesa-examples/tree/main/examples/hex_snowflake)
- [color_patches](https://github.com/projectmesa/mesa-examples/tree/main/examples/color_patches)
- [conways_game_of_life](https://github.com/projectmesa/mesa-examples/tree/main/examples/conways_game_of_life)

The [migration guide](https://github.com/projectmesa/mesa/blob/main/docs/migration_guide.md#time-and-schedulers) might contain more information about how to move from schedulers to the AgentSet.
