### ISSUE TITLE
Close stale issues?

### ISSUE THREAD

**Issue by Corvince** [projectmesa/mesa#685]
Every time I am in the mood to look at some mesa issues, I am overwhelmed and don't know where to start. But actually most of the issues are in this limbo of "something could be done here or someone maybe has already started". This makes it hard to judge about whether to close them or not. Therefore I propose to add the [stale bot](https://github.com/marketplace/stale) to the mesa repo.

The stale bot automatically replies to issues that haven't seen any activity for xx days and warns that it will be closed yy days later (and then closes them). Importantly, we can also provide label tags for issues that should never be closed (e.g. the bug label)

I think this would be a nice and somewhat standardized way to get rid of old issues and keep the issue tracker clean. And of course the nice thing about GitHub issues is that they can always be reopened, if interest returns. 

What do you think? Things to decide:

- [ ] Days until stale message (default: 60)
- [ ] Days until closed (default: 7)
- [ ] Labels to prevent closing (bug, ???)

**Comment by jackiekazil** [comment]
I have been going through them and curating. The method to curate tickets that I have been using is as follows.... 

- Tickets with no labels are accessed first.
- While action is being determined, it is given a 'triage' label. (These are usually looked at second.)
- Things that have distinct actions that can be done are labeled 'backlog' or 'discuss'. 
- Things that do not, are closed. 

My biggest concern is that sometimes we all go into a hole, because most of us are doing this after hours, and we auto close a ticket that has something that is important it in. 

I am on the fence on auto processing. I will let others chime in.

**Comment by rht** [comment]
Auto-closing has several problems:
1. creates duplicate issues
2. renders the issue search unusable because of the explosion of closed issues
3. partial solutions that are commented in one of the duplicates may not be read by viewers of other duplicate issues

Instead, it would be better to soft-close an issue by labeling it as inactive, and so it can be excluded in search.

**Comment by rht** [comment]
Can this issue be closed? <200 issues are not that many, and are still manageable.
