### ISSUE TITLE
I am trying to spawn agent every X tick

### ISSUE THREAD

**Issue by AnneHelstam** [projectmesa/mesa#689]
Thank you for a great tool! 

I am trying to spawn one agent at a time every X tick, and am having issues figuring this out. 

Currently I have this code, and cannot get it to add more than one agent. The idea is that the agents must move either up, down, left or right depending on their type (color) and then be removed. We wish to have the agents wait in line to start moving towards their spot to be removed whenever that spot is free but can currently only spawn one agent, and not add any after that agent is removed. 

```
class Airport(Model):
        def __init__(self, n_agents, agent_type, height= 20, width= 20):
                super().__init__()
                self.schedule = SimultaneousActivation(self) 
                self.grid = SingleGrid(21, 21, torus=False)
                self.agent_type = agent_type
                self.happy = 0

                # Defines agent type
                
                for i in range(n_agents):
                                if self.random.randint(0, 4) == 0:
                                        agent_type = 0
                                elif self.random.randint(0, 4) == 1:
                                        agent_type = 1
                                elif self.random.randint(0, 4) == 2:
                                        agent_type = 2
                                else:
                                        agent_type = 3

                # Add the agent to the model
                coords = (self.random.randrange(10,11), self.random.randrange(10,11))
                a = Airplane(i, self, n_agents, agent_type)
                self.schedule.add(a)
                self.grid.place_agent(a, coords)
```

**Comment by Corvince** [comment]
Hello! 

There are quite a few issues with your code. I would suggest to learn a bit more about how python works before building up your model. Some observations:

You first set `self.agent_type` to `agent_type`, but don't seem to use that afterwards. 
The you loop over `n_agents`. It appears you then want to check if a random integer is either 1,2,3 or 4. But you actually create 3 different random numbers, greatly increasing the probability that agent_type will be 3. You could simply write `agent_type = self.random.randint(0,4)`. 
But regardless, you overwrite that agent_type with every loop iteration. In the end you will only have exactly 1 `i` and 1 `agent_type`.  You than create one `Airplane` with these. If you want to create more Airplanes simultaneously you have to put the creation inside the for loop. If you want to create the Airplane when an Airplane is removed the easiest way to do it would be inside the Airplane class, simply following the creation procedure you already have.

Since this is not an issue with mesa itself, I am going to close this. But please feel very free to ask further questions on the [mailing list](https://groups.google.com/forum/#!forum/projectmesa)!
