### ISSUE TITLE
Docs in this repo or separate repo?

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#73]
Right now, we have the docs here:  https://github.com/projectmesa/mesa/tree/master/docs
Do we want to keep them there or move them to a separate repo? 

I have see both ways, so I am open. 
Related #74

**Comment by dmasad** [comment]
With Sphinx, the documentation should be at least in part auto-generated from the source, right? If so, my inclination would be to have it all be one repo: that way, someone can make a branch or fork and update the features and the associated documentation together, and then merge them into master together. Otherwise, we need to manually keep track of which branch of the documentation is associated with which branch of the package itself.

**Comment by jackiekazil** [comment]
That is a good point. We will leave it in this repo.
