### ISSUE TITLE
Fix base classes

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#81]
The base classes for Agent and Model were put together pretty haphazardly, and are poorly documented. Fix. In particular, there are some assumptions (e.g. Agent taking a model as a constructor argument) that don't reflect most of the models we've written so far.

**Comment by ReblochonMasque** [comment]
Is that what the branch "rewrite model" is about?

**Comment by jackiekazil** [comment]
@ReblochonMasque  -- That is a branch that I have been working off of to make how we organize models easier to understand, along with adding more convention to file structures. This isn't a direct reflection of this ticket. I did add this ticket to rebirth, because my assumption is that it will break backwards compatibility.

**Comment by jackiekazil** [comment]
@dmasad ... I can't remember the origin motivation of this conversation. I believe this has been fixed? or not? If not, can you describe in further detail?

**Comment by jackiekazil** [comment]
This is happening in other ways. Closing this for clean up now.
