### ISSUE TITLE
[NetworkGrid] change G.node to G.nodes

### ISSUE THREAD

**Issue by hoyeoplee** [projectmesa/mesa#812]
I recently run the "Virus infection example."
However, it not works!

My networkx version is 2.4, and there doesn't exist method "G.node" anymore, instead there is a "G.nodes."
When replace the "G.node" to "G.nodes" in space.py (line nos. 812, 817 of public version), it works.

So, I recommend changing the code of the next version for the compatibility of recent networkx version.
Thanks  for reading :)

**Comment by akbaritabar** [comment]
Same here (with "boltzmann_wealth_model_network" and "virus_on_network" examples), changing space.py solved it. I was going to submit a pull request with the change mentioned above, while I thought maybe maintainers would like to keep backward compatibility with earlier networkx versions?! Otherwise I will happily submit.

**Comment by tpike3** [comment]
This is due to an upgrade in Networkx, if you install from the git repository 

`pip install -e git+https://github.com/projectmesa/mesa#egg=mesa`

then you will not have this issues. I think the repo will be pushed to PyPi before too long, to correct this.
