### ISSUE TITLE
Frames per second slider

### ISSUE THREAD

**Issue by wouter-duchateau** [projectmesa/mesa#813]
Hi everyone,

I don't know whether this is the right channel to post a question in but I am fairly new to Mesa and wanted to ask whether (and how) it is possible to increase the fps further than 20. 

I am trying to model kinematics for robots moving in a grid environment by linearizing different 'maneuvers' (accelerating, decelerating, turning,...), this means that moving one cell can require several ticks. Since one step takes averagely 5 ticks, I was wondering whether the fps could be increased to increase the speed in the visualization.

**Comment by Corvince** [comment]
This is currently not so easy to do, you would have to change the runcontrol JavaScript file of mesa directly.
However one handy hack is to set the fps to 0, which actually causes the visualization to run as fast as possible.

 Let me know if this is good enough for your, otherwise I can look up and tell what exactly you have to change (I'm on mobile right now)

**Comment by wouter-duchateau** [comment]
That indeed solves it for now, thank you!
