### ISSUE TITLE
Increase Visualisation Speed

### ISSUE THREAD

**Issue by alabrazi** [projectmesa/mesa#867]
**What's the problem this feature will solve?**
Increase the speed of time by 20 times in visualisation is not enough 

**Describe the solution you'd like**
Make it possible for the user to determine the factor by which the speed of simulation run instead of 20 step slider 

**Additional context**

**Comment by dmasad** [comment]
You can edit the `fpsControl`  object in [runcontrol.js](https://github.com/projectmesa/mesa/blob/master/mesa/visualization/templates/js/runcontrol.js#L101) to increase the maximum available frame-rate. But keep in mind that just because you set the frame-rate to 60 fps doesn't mean it will actually render that fast. Between the time it takes to run each iteration and draw it on the screen, it can easily take longer than whatever the frame-rate is.

**Comment by alabrazi** [comment]
Thanks! I figured it out. One note if someone is trying to do the same. After changing the code in runcontrol.js delete the cash in the browser otherwise Brave browser will not reflect the changes. This issue mainly happen in Brave browser but not in Safari.
